on:
  workflow_dispatch:
    
  pull_request:
    types: [opened, synchronize]
  

jobs:
  ESLint-Evaluator:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch ESLint evaluator
        uses: stefanoeb/eslint-action@1.0.2

