on:
  workflow_dispatch:
    
  pull_request:
    types: [opened, synchronize]
  
jobs:
  ESLint-Backend-Evaluator:
    runs-on: ubuntu-latest
    name: ESLint Backend
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Evaluator
        run: |
          cd app/backend
          npm i
          npm run lint

  ESLint-Frontend-Evaluator:
    runs-on: ubuntu-latest
    name: ESLint Frontend
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Evaluator
        run: |
          cd app/frontend
          npm i
          npm run lint
          npm run lint:styles

  Backend-Tests:
    runs-on: ubuntu-latest
    name: Backend Tests
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          cd app/backend
          npm i
          npm test