on:
  workflow_dispatch:
    
  pull_request:
    types: [opened, synchronize]
  

jobs:
  ESLint-Evaluator:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: ESLint Backend Evaluator
        run: |
          cd app/backend
          npm i
          npm run lint

      - name: ESLint Frontend Evaluator
        run: |
          cd app/frontend
          npm i
          npm run lint
          npm run lint:styles